version: '3.8'

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    ports:
      - '48945:5432'
